/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AnimatedOutlet: (typeof import('../components/page'))['AnimatedOutlet']
  const IconSolarAddCircleLinear: (typeof import('~icons/solar/add-circle-linear.jsx'))['default']
  const IconSolarErrorCircle: (typeof import('~icons/solar/error-circle.jsx'))['default']
  const IconSolarInboxArchiveOutline: (typeof import('~icons/solar/inbox-archive-outline.jsx'))['default']
  const IconSolarLoadingCircle: (typeof import('~icons/solar/loading-circle.jsx'))['default']
  const PageTransition: (typeof import('../components/page'))['PageTransition']
  const SocketIOState: (typeof import('../hooks/socket-io'))['SocketIOState']
  const SocketIOStateIndicator: (typeof import('../components/socket-io-indicator'))['SocketIOStateIndicator']
  const TailwindIndicator: (typeof import('../components/tailwind-indicator'))['TailwindIndicator']
  const WebsocketState: (typeof import('../hooks/websocket'))['WebsocketState']
  const cn: (typeof import('../utils/ui'))['cn']
  const fancyBox: (typeof import('../components/fancy-box'))['default']
  const getResourceUrl: (typeof import('../utils/url'))['getResourceUrl']
  const isTauri: (typeof import('../utils/env'))['isTauri']
  const sleep: (typeof import('../utils/index'))['sleep']
  const socketIoIndicator: (typeof import('../components/socket-io-indicator'))['default']
  const swr: (typeof import('../hooks/swr'))['default']
  const useBrowserNotification: (typeof import('../hooks/use-notification'))['useBrowserNotification']
  const useFetch: (typeof import('../hooks/ofetch'))['useFetch']
  const useGlobalMutation: (typeof import('../hooks/useGlobalMutation'))['default']
  const useNotification: (typeof import('../hooks/use-notification'))['default']
  const useScroll: (typeof import('../hooks/useScroll'))['default']
  const useSocketIO: (typeof import('../hooks/socket-io'))['useSocketIO']
  const useSocketIOWithHandler: (typeof import('../hooks/socket-io'))['useSocketIOWithHandler']
  const useTauriNotification: (typeof import('../hooks/use-notification'))['useTauriNotification']
}
