/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AnimatedOutlet: (typeof import('../components/page'))['AnimatedOutlet']
  const IconSolarInboxArchiveOutline: (typeof import('~icons/solar/inbox-archive-outline.jsx'))['default']
  const PageTransition: (typeof import('../components/page'))['PageTransition']
  const TailwindIndicator: (typeof import('../components/tailwind-indicator'))['TailwindIndicator']
  const cn: (typeof import('../utils/ui'))['cn']
}
