/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefaultFooter: typeof import('./../layouts/common/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./../layouts/common/DefaultHeader.vue')['default']
    Greet: typeof import('./../components/Greet.vue')['default']
    HeaderElement: typeof import('./../layouts/common/components/HeaderElement.vue')['default']
    IconFluentDiversity48Regular: typeof import('~icons/fluent/diversity48-regular')['default']
    IconFluentDocumentAdd48Regular: typeof import('~icons/fluent/document-add48-regular')['default']
    IconFluentQuestionCircle48Regular: typeof import('~icons/fluent/question-circle48-regular')['default']
    IconFluentSettings48Regular: typeof import('~icons/fluent/settings48-regular')['default']
    IconFluentShapes48Regular: typeof import('~icons/fluent/shapes48-regular')['default']
    IconFluentThumbLike48Regular: typeof import('~icons/fluent/thumb-like48-regular')['default']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
